# CMake generated Testfile for 
# Source directory: C:/Users/jonas/Documents/trit
# Build directory: C:/Users/jonas/Documents/trit/build_crypto
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_architecture_v2]=] "C:/Users/jonas/Documents/trit/build_crypto/test_architecture_v2.exe")
set_tests_properties([=[test_architecture_v2]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;68;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_first_silicon_bringup]=] "C:/Users/jonas/Documents/trit/build_crypto/test_first_silicon_bringup.exe")
set_tests_properties([=[test_first_silicon_bringup]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;73;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_redo_wal_v2]=] "C:/Users/jonas/Documents/trit/build_crypto/test_redo_wal_v2.exe")
set_tests_properties([=[test_redo_wal_v2]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;79;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_migration_v2]=] "C:/Users/jonas/Documents/trit/build_crypto/test_migration_v2.exe")
set_tests_properties([=[test_migration_v2]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;117;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_vfs_rename]=] "C:/Users/jonas/Documents/trit/build_crypto/test_vfs_rename.exe")
set_tests_properties([=[test_vfs_rename]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;287;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_encrypted_volume]=] "C:/Users/jonas/Documents/trit/build_crypto/test_encrypted_volume.exe")
set_tests_properties([=[test_encrypted_volume]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;316;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_encrypted_volume_parser]=] "C:/Users/jonas/Documents/trit/build_crypto/test_encrypted_volume_parser.exe")
set_tests_properties([=[test_encrypted_volume_parser]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;321;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_host_runtime]=] "C:/Users/jonas/Documents/trit/build_crypto/test_host_runtime.exe")
set_tests_properties([=[test_host_runtime]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;335;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_checkpoint_replay_process]=] "C:/Users/jonas/Documents/trit/build_crypto/trit_checkpoint_replay.exe" "C:/Users/jonas/Documents/trit/build_crypto/host_runtime_checkpoint_bundle" "--steps" "32" "--require-halt" "--json")
set_tests_properties([=[test_checkpoint_replay_process]=] PROPERTIES  DEPENDS "test_host_runtime" WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;338;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_architecture_contract]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tools/generate_architecture_contract.py" "--check")
set_tests_properties([=[test_architecture_contract]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;353;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_agent_tooling]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_agent_tooling.py")
set_tests_properties([=[test_agent_tooling]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;358;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_system_benchmark_contract]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_system_benchmark_contract.py")
set_tests_properties([=[test_system_benchmark_contract]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;361;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_performance_baseline]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_performance_baseline.py")
set_tests_properties([=[test_performance_baseline]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;365;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_external_benchmark_assets]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_external_benchmark_assets.py")
set_tests_properties([=[test_external_benchmark_assets]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;369;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_bitnet_external_execution]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_bitnet_external_execution.py")
set_tests_properties([=[test_bitnet_external_execution]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;373;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_symbolic_guest]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_symbolic_guest.py")
set_tests_properties([=[test_symbolic_guest]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;377;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_symbolic_diagnostics]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_symbolic_diagnostics.py")
set_tests_properties([=[test_symbolic_diagnostics]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;381;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_encrypted_volume_cli]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_encrypted_volume_cli.py")
set_tests_properties([=[test_encrypted_volume_cli]=] PROPERTIES  ENVIRONMENT "TRIT_VOLUME_BINARY=C:/Users/jonas/Documents/trit/build_crypto/trit_volume.exe" WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;385;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_posix_wrappers]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "-m" "unittest" "tools.tests.test_posix_wrappers")
set_tests_properties([=[test_posix_wrappers]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;391;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_source_manifest_generation]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tests/test_source_manifest_generation.py")
set_tests_properties([=[test_source_manifest_generation]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;395;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_compiler_corpus_gate]=] "C:/Users/jonas/AppData/Local/Programs/Python/Python312/python.exe" "C:/Users/jonas/Documents/trit/tools/compiler_corpus_gate.py" "--binary" "C:/Users/jonas/Documents/trit/build_crypto/test_compiler_corpus_gate.exe")
set_tests_properties([=[test_compiler_corpus_gate]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;399;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_production_hardening]=] "C:/Users/jonas/Documents/trit/build_crypto/test_production_hardening.exe")
set_tests_properties([=[test_production_hardening]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;411;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_syscall_pointer_fuzz]=] "C:/Users/jonas/Documents/trit/build_crypto/test_syscall_pointer_fuzz.exe")
set_tests_properties([=[test_syscall_pointer_fuzz]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;414;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_compiler_abi_contract]=] "C:/Users/jonas/Documents/trit/build_crypto/test_compiler_abi_contract.exe")
set_tests_properties([=[test_compiler_abi_contract]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;417;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_executable_abi_v3]=] "C:/Users/jonas/Documents/trit/build_crypto/test_executable_abi_v3.exe")
set_tests_properties([=[test_executable_abi_v3]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;420;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[test_symbolic_encodings]=] "C:/Users/jonas/Documents/trit/build_crypto/test_symbolic_encodings.exe")
set_tests_properties([=[test_symbolic_encodings]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;479;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_isa_encoding]=] "C:/Users/jonas/Documents/trit/build_crypto/next_isa_encoding.exe")
set_tests_properties([=[next_isa_encoding]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;636;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_assembler_goldens]=] "C:/Users/jonas/Documents/trit/build_crypto/next_assembler_goldens.exe")
set_tests_properties([=[next_assembler_goldens]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;639;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_assembler_tcl_parity]=] "C:/Users/jonas/Documents/trit/build_crypto/next_assembler_tcl_parity.exe")
set_tests_properties([=[next_assembler_tcl_parity]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;642;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_vm_core]=] "C:/Users/jonas/Documents/trit/build_crypto/next_vm_core.exe")
set_tests_properties([=[next_vm_core]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;645;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_compiler_pipeline]=] "C:/Users/jonas/Documents/trit/build_crypto/next_compiler_pipeline.exe")
set_tests_properties([=[next_compiler_pipeline]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;648;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_compiler_native_ulib]=] "C:/Users/jonas/Documents/trit/build_crypto/next_compiler_native_ulib.exe")
set_tests_properties([=[next_compiler_native_ulib]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;651;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_compiler_phase_c5_pred]=] "C:/Users/jonas/Documents/trit/build_crypto/next_compiler_phase_c5_pred.exe")
set_tests_properties([=[next_compiler_phase_c5_pred]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;654;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_runtime_ulib_sdk]=] "C:/Users/jonas/Documents/trit/build_crypto/next_runtime_ulib_sdk.exe")
set_tests_properties([=[next_runtime_ulib_sdk]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;657;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_kernel_native_os]=] "C:/Users/jonas/Documents/trit/build_crypto/next_kernel_native_os.exe")
set_tests_properties([=[next_kernel_native_os]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;660;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_kernel_native_phase_d]=] "C:/Users/jonas/Documents/trit/build_crypto/next_kernel_native_phase_d.exe")
set_tests_properties([=[next_kernel_native_phase_d]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;663;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_vfs_persistence]=] "C:/Users/jonas/Documents/trit/build_crypto/next_vfs_persistence.exe")
set_tests_properties([=[next_vfs_persistence]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;666;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_vfs_recovery]=] "C:/Users/jonas/Documents/trit/build_crypto/next_vfs_recovery.exe")
set_tests_properties([=[next_vfs_recovery]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;669;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_process_ipc_scheduler]=] "C:/Users/jonas/Documents/trit/build_crypto/next_process_ipc_scheduler.exe")
set_tests_properties([=[next_process_ipc_scheduler]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;672;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_scheduler_acceptance]=] "C:/Users/jonas/Documents/trit/build_crypto/next_scheduler_acceptance.exe")
set_tests_properties([=[next_scheduler_acceptance]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;675;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_drivers_hal]=] "C:/Users/jonas/Documents/trit/build_crypto/next_drivers_hal.exe")
set_tests_properties([=[next_drivers_hal]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;678;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_graphics_gui]=] "C:/Users/jonas/Documents/trit/build_crypto/next_graphics_gui.exe")
set_tests_properties([=[next_graphics_gui]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;681;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_apps_consumer_bundle]=] "C:/Users/jonas/Documents/trit/build_crypto/next_apps_consumer_bundle.exe")
set_tests_properties([=[next_apps_consumer_bundle]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;684;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_apps_desktop_shell]=] "C:/Users/jonas/Documents/trit/build_crypto/next_apps_desktop_shell.exe")
set_tests_properties([=[next_apps_desktop_shell]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;687;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_apps_golden_snapshots]=] "C:/Users/jonas/Documents/trit/build_crypto/next_apps_golden_snapshots.exe")
set_tests_properties([=[next_apps_golden_snapshots]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;690;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
add_test([=[next_full_system_release]=] "C:/Users/jonas/Documents/trit/build_crypto/next_full_system_release.exe")
set_tests_properties([=[next_full_system_release]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/jonas/Documents/trit" _BACKTRACE_TRIPLES "C:/Users/jonas/Documents/trit/CMakeLists.txt;693;add_test;C:/Users/jonas/Documents/trit/CMakeLists.txt;0;")
