import fs from "node:fs";
import path from "node:path";
import type { Capability, Difficulty } from "../../src/ternary/contracts";
import { hash, invariant } from "./util";
import type { Case } from "./worker";

export const REVISION = "pilot-2026-09-a";
export const SUPPORT = `
fn q(n: t40, d: t40) -> t40 { var s: t40 = 1; var x: t40 = n; if (x < 0) { s = 0-1; x = 0-x; } var r: t40 = 0; while (x >= d) { x = x-d; r = r+1; } return r*s; }
fn mod(n: t40, d: t40) -> t40 { var r: t40 = n-q(n,d)*d; if (r < 0) { r = r+d; } return r; }
fn p3(w: t40) -> t40 { var r: t40 = 1; var i: t40 = 0; while (i < w) { r = r*3; i = i+1; } return r; }
fn digit(n: t40, i: t40) -> t40 { return mod(q(n,p3(i)),3); }
fn sg(n: t40) -> t40 { if (n < 0) { return 0-1; } if (n > 0) { return 1; } return 0; }
fn lo(a: t40, b: t40) -> t40 { if (a < b) { return a; } return b; }
fn hi(a: t40, b: t40) -> t40 { if (a > b) { return a; } return b; }
fn wrap(n: t40, w: t40) -> t40 { var b: t40 = p3(w); var h: t40 = q(b-1,2); return mod(n+h,b)-h; }
`;
export const LANGUAGE_REFERENCE = "Use Trit fn/var/if/while syntax, t40 integer scalars, and return. Numeric literals and intermediate values in this task fit t40. The starter supplies q(n,d) (truncate division toward zero, d>0), mod(n,d) (nonnegative remainder), p3(w), digit(n,i) (base-three digit at zero-based position i), sg, lo, hi, and wrap(n,w) (balanced signed w-trit wrap). You may replace solution.trit, including helpers. Additional helper names must begin with local_. No imports, host calls, strings, assembly, or main; the grader supplies main. Preserve solve(a: t40,b: t40,c: t40)->t40. Only exact integer behavior is graded.";
type Oracle = (a: number,b: number,c: number) => number;
interface Definition { id: string; capability: Capability; difficulty: Difficulty; title: string; requirements: string; reference: string; wrong: string; domain: [number[],number[],number[]]; oracle: Oracle }
export interface TaskPackage {
  id: string; capability: Capability; difficulty: Difficulty; title: string; requirements: string; specification: string;
  starter: Record<string,string>; reference: string; mutants: Array<{ name: string; source: string; targetCaseIds: string[] }>;
  publicCases: Case[]; privateCases: Case[]; feedback: Case[][]; probes: Case[][];
  qualificationCases: Case[]; exhaustive: boolean; invariants: string[]; checkerHash: string; packageHash: string;
}
const range = (a: number,b: number) => Array.from({length:b-a+1},(_,i)=>a+i);
const trits = [-1,0,1], symbols = [0,1,2];
const div = (n: number,d: number) => Number(BigInt(n)/BigInt(d));
const mod = (n: number,d: number) => Number((BigInt(n)%BigInt(d)+BigInt(d))%BigInt(d));
const digits = (n: number,w: number) => Array.from({length:w},(_,i)=>Math.floor(n/3**i)%3);
const pack = (d: number[]) => d.reduce((a,x,i)=>a+x*3**i,0);
const balanced = (n: number,w: number) => mod(n+(3**w-1)/2,3**w)-(3**w-1)/2;
const small = [trits,trits,trits] as [number[],number[],number[]];
const source = (body: string) => SUPPORT + `\nfn solve(a: t40, b: t40, c: t40) -> t40 { ${body} }\n`;
const defs: Definition[] = [];
function task(capability: Capability, suffix: number, title: string, requirements: string, domain: Definition["domain"], oracle: Oracle, body: string, wrong: string) {
  defs.push({ id: `${capability}-${String(suffix).padStart(2,"0")}`, capability, difficulty: suffix <= 2 ? "introductory" : suffix <= 4 ? "intermediate" : "advanced", title, requirements, domain, oracle, reference: source(body), wrong: source(wrong) });
}

task("representation",1,"Balanced digit place value","a,b,c are balanced trits (-1,0,+1), most-significant first. Return their exact signed base-three integer value.",small,(a,b,c)=>Number(9n*BigInt(a)+3n*BigInt(b)+BigInt(c)),"return 9*a+3*b+c;","return 9*(a+1)+3*(b+1)+(c+1);");
task("representation",2,"Normalize redundant digits","a,b,c are redundant digits in [-2,2], least-significant first. Normalize their value into three balanced trits with wrap on overflow. Return the normalized signed integer.",[range(-2,2),range(-2,2),range(-2,2)],(a,b,c)=>balanced(a+3*b+9*c,3),"return wrap(a+3*b+9*c,3);","return a+3*b+9*c;");
task("representation",3,"Carry across a three-trit word","a,b are signed three-trit words [-13,13]; c is carry-in (-1,0,1). Add them, returning 100*carryOut+wrappedWord; carryOut is -1,0,1 and wrappedWord is in [-13,13].",[range(-13,13),range(-13,13),trits],(a,b,c)=>{const n=a+b+c,w=balanced(n,3);return 100*(n-w)/27+w;},"var n:t40=a+b+c; var r:t40=wrap(n,3); return 100*q(n-r,27)+r;","var n:t40=a+b+c; return wrap(n,3);");
task("representation",4,"Saturating width conversion","Add signed integers a and b. Saturate to the balanced c-trit range [-(3^c-1)/2, +(3^c-1)/2], where c is 1..5.",[[-121,-40,-14,-1,0,1,14,40,121],[-41,-13,-1,0,1,13,41],range(1,5)],(a,b,c)=>Math.max(-(3**c-1)/2,Math.min((3**c-1)/2,a+b)),"var h:t40=q(p3(c)-1,2); return hi(0-h,lo(h,a+b));","return wrap(a+b,c);");
task("representation",5,"Exact fixed-point rounding","Return the nearest integer to the exact rational a*b/(2*3^c). Ties round to the even integer; handle negative products symmetrically. c is 0..3.",[range(-9,9),range(-9,9),range(0,3)],(a,b,c)=>{const n=BigInt(a)*BigInt(b),d=2n*3n**BigInt(c),s=n<0n?-1n:1n,x=n*s,r=x/d,rem=x%d;return Number(s*(r+(2n*rem>d||2n*rem===d&&r%2n!==0n?1n:0n)));},"var n:t40=a*b; var s:t40=sg(n); var x:t40=n*s; var d:t40=2*p3(c); var r:t40=q(x,d); var rem:t40=x-r*d; if (2*rem>d) { r=r+1; } else { if (2*rem==d) { if (mod(r,2)==1) { r=r+1; } } } return s*r;","return q(a*b,2*p3(c));");
task("representation",6,"Validate packed two-bit trits","a encodes b trits in two-bit cells, least-significant first: cell 0 means 0, 1 means +1, 2 means -1, and 3 is invalid. Decode the low b cells, then add 27*c. Return 999 if any decoded cell is invalid. b is 1..3.",[range(0,63),range(1,3),trits],(a,b,c)=>{let result=27*c;for(let i=0;i<b;i++){const d=Math.floor(a/4**i)%4;if(d===3)return 999;result+=(d===2?-1:d)*3**i;}return result;},"var n:t40=a; var i:t40=0; var r:t40=27*c; while(i<b){var d:t40=mod(n,4);if(d==3){return 999;}if(d==2){d=0-1;}r=r+d*p3(i);n=q(n,4);i=i+1;}return r;","var n:t40=a;var i:t40=0;var r:t40=27*c;while(i<b){var d:t40=mod(n,4);if(d==2){d=0-1;}r=r+d*p3(i);n=q(n,4);i=i+1;}return r;");

task("logic",1,"Strong Kleene composition","Values -1,0,1 mean false, unknown, true. AND takes the minimum and OR the maximum. Evaluate (a AND b) OR c.",small,(a,b,c)=>Math.max(Math.min(a,b),c),"return hi(lo(a,b),c);","return lo(a,hi(b,c));");
task("logic",2,"Unknown-preserving implication","Under strong Kleene semantics, NOT negates, OR=max and AND=min. Evaluate (a implies b) AND c, with implication defined as NOT a OR b.",small,(a,b,c)=>Math.min(Math.max(-a,b),c),"return lo(hi(0-a,b),c);","if(a==0){return c;}return lo(hi(0-a,b),c);");
task("logic",3,"Evidence-aware equivalence","Return unknown (0) if any of a,b,c is unknown (0). Otherwise return true (+1) if all three agree and false (-1) if they differ. Two unknown values are not proof of equivalence.",small,(a,b,c)=>[a,b,c].includes(0)?0:a===b&&b===c?1:-1,"if(a==0){return 0;}if(b==0){return 0;}if(c==0){return 0;}if(a==b){if(b==c){return 1;}}return 0-1;","if(a==b){if(b==c){return 1;}}return 0-1;");
task("logic",4,"Lexicographic comparison with unknowns","a,b pack three symbols in base three, most-significant compared first; symbols 0,1,2 mean false,unknown,true. c=0 compares ordinary digit order. c=1 returns unknown (0) when the first differing pair contains symbol 1. c=2 reverses ordinary ordering. Return -1,0,+1.",[range(0,26),range(0,26),symbols],(a,b,c)=>{const x=digits(a,3).reverse(),y=digits(b,3).reverse();for(let i=0;i<3;i++){if(x[i]===y[i])continue;if(c===1&&(x[i]===1||y[i]===1))return 0;return Math.sign(x[i]-y[i])*(c===2?-1:1);}return 0;},"var i:t40=2;while(i>=0){var x:t40=digit(a,i);var y:t40=digit(b,i);if(x!=y){if(c==1){if(x==1){return 0;}if(y==1){return 0;}}var r:t40=sg(x-y);if(c==2){r=0-r;}return r;}i=i-1;}return 0;","var r:t40=sg(a-b);if(c==2){r=0-r;}return r;");
task("logic",5,"Three-way branch contract","a selects a branch: -1 returns b, 0 returns 0, +1 returns c. b and c are balanced trits. Unknown must not be coerced to a binary else branch.",small,(a,b,c)=>a<0?b:a>0?c:0,"if(a<0){return b;}if(a>0){return c;}return 0;","if(a>0){return c;}return b;");
task("logic",6,"Enabled saturating state transition","a is current state, b is a signed event, c is control. c=-1 resets to 0; c=0 holds a; c=1 applies a+b saturated to [-1,1]. All inputs are balanced trits.",small,(a,b,c)=>c<0?0:c===0?a:Math.max(-1,Math.min(1,a+b)),"if(c<0){return 0;}if(c==0){return a;}return hi(0-1,lo(1,a+b));","if(c<0){return 0;}return hi(0-1,lo(1,a+b));");

task("learning",1,"Unfamiliar symbol alphabet","Symbols 0,1,2 denote +1,-1,0 respectively. a,b,c are these symbols, least-significant first. Return the signed value represented by the three symbols.",[symbols,symbols,symbols],(a,b,c)=>[1,-1,0][a]+3*[1,-1,0][b]+9*[1,-1,0][c],"var x:t40=0;var y:t40=0;var z:t40=0;if(a==0){x=1;}if(a==1){x=0-1;}if(b==0){y=1;}if(b==1){y=0-1;}if(c==0){z=1;}if(c==1){z=0-1;}return x+3*y+9*z;","return (a-1)+3*(b-1)+9*(c-1);");
task("learning",2,"Noncommutative unfamiliar operator","On symbols 0,1,2 define x diamond y = (x+2*y) modulo 3. Return (a diamond b) diamond c. Parentheses are significant.",[symbols,symbols,symbols],(a,b,c)=>mod(mod(a+2*b,3)+2*c,3),"return mod(mod(a+2*b,3)+2*c,3);","return mod(a+2*mod(b+2*c,3),3);");
task("learning",3,"A small unfamiliar instruction set","a encodes three base-three opcodes, least-significant executed first. Initial register is b. Opcode 0 adds c; 1 negates; 2 multiplies by three. After each instruction wrap into the signed three-trit range [-13,13]. Return final register.",[range(0,26),range(-13,13),trits],(a,b,c)=>digits(a,3).reduce((r,op)=>balanced(op===0?r+c:op===1?-r:3*r,3),b),"var r:t40=b;var i:t40=0;while(i<3){var op:t40=digit(a,i);if(op==0){r=r+c;}if(op==1){r=0-r;}if(op==2){r=r*3;}r=wrap(r,3);i=i+1;}return r;","var r:t40=b;var i:t40=2;while(i>=0){var op:t40=digit(a,i);if(op==0){r=r+c;}if(op==1){r=0-r;}if(op==2){r=r*3;}r=wrap(r,3);i=i-1;}return r;");
task("learning",4,"Banked ternary addressing","a has three unsigned base-three digits: low=column, middle=row, high=bank. A bank spans 81 words. Row stride is b (3..9), and c is a base offset (0..2). Return 81*bank+b*row+column+c.",[range(0,26),range(3,9),symbols],(a,b,c)=>{const d=digits(a,3);return 81*d[2]+b*d[1]+d[0]+c;},"return 81*digit(a,2)+b*digit(a,1)+digit(a,0)+c;","return 9*digit(a,2)+b*digit(a,1)+digit(a,0)+c;");
task("learning",5,"Composed ring transformations","Start with signed a in [-13,13]. b packs three operations low-first: 0 adds c, 1 maps x to 2*x+c, 2 maps x to -x+c. Each step wraps into [-13,13]. Return final state. c is -2..2.",[range(-13,13),range(0,26),range(-2,2)],(a,b,c)=>digits(b,3).reduce((x,op)=>balanced((op===0?x:op===1?2*x:-x)+c,3),a),"var r:t40=a;var i:t40=0;while(i<3){var op:t40=digit(b,i);if(op==1){r=2*r;}if(op==2){r=0-r;}r=wrap(r+c,3);i=i+1;}return r;","var r:t40=a;var i:t40=0;while(i<3){var op:t40=digit(b,i);if(op==1){r=2*r;}if(op==2){r=0-r;}r=hi(0-13,lo(13,r+c));i=i+1;}return r;");
task("learning",6,"Changing the meaning of an unknown write","a packs four write symbols low-first, encoding -1,0,+1 as 0,1,2. Initial register b is a balanced trit. Policy c: 0 writes every value; 1 ignores unknown writes; 2 makes unknown absorbing (once 0 is seen or initial b=0, later writes cannot change it). Return register.",[range(0,80),trits,symbols],(a,b,c)=>digits(a,4).reduce((r,s)=>{const x=s-1;if(c===1&&x===0)return r;if(c===2&&r===0)return 0;return x;},b),"var r:t40=b;var i:t40=0;while(i<4){var x:t40=digit(a,i)-1;var write:t40=1;if(c==1){if(x==0){write=0;}}if(c==2){if(r==0){write=0;}}if(write==1){r=x;}i=i+1;}return r;","return digit(a,3)-1;");

task("algorithms",1,"Search a packed trit sequence","a packs six symbols (0,1,2 represent -1,0,+1), low-first. Find balanced trit b at the first index >=c, c=0..5. Return its index or -1 if absent.",[range(0,728),trits,range(0,5)],(a,b,c)=>{const d=digits(a,6);for(let i=c;i<6;i++)if(d[i]-1===b)return i;return -1;},"var i:t40=c;while(i<6){if(digit(a,i)-1==b){return i;}i=i+1;}return 0-1;","var i:t40=0;while(i<6){if(digit(a,i)-1==b){return i;}i=i+1;}return 0-1;");
task("algorithms",2,"Order and rotate a ternary sequence","Sort the four low-first base-three symbols packed in a. b=0 means ascending and b=1 descending. Rotate the sorted array left by c positions (0..3), then repack low-first.",[range(0,80),[0,1],range(0,3)],(a,b,c)=>{const d=digits(a,4).sort((x,y)=>b?y-x:x-y);return pack([...d.slice(c),...d.slice(0,c)]);},"var n0:t40=0;var n1:t40=0;var i:t40=0;while(i<4){var d:t40=digit(a,i);if(d==0){n0=n0+1;}if(d==1){n1=n1+1;}i=i+1;}var r:t40=0;i=0;while(i<4){var j:t40=mod(i+c,4);if(b==1){j=3-j;}var d:t40=2;if(j<n0){d=0;}else{if(j<n0+n1){d=1;}}r=r+d*p3(i);i=i+1;}return r;","var n0:t40=0;var n1:t40=0;var i:t40=0;while(i<4){var d:t40=digit(a,i);if(d==0){n0=n0+1;}if(d==1){n1=n1+1;}i=i+1;}var r:t40=0;i=0;while(i<4){var j:t40=i;if(b==1){j=3-j;}var d:t40=2;if(j<n0){d=0;}else{if(j<n0+n1){d=1;}}r=r+d*p3(i);i=i+1;}return r;");
task("algorithms",3,"Index a ternary tree","Nodes use level-order storage. c is the root index (0 or 1); a is a parent index; b=-1,0,+1 selects left,middle,right child. Return the child index; return -1 if a<c. Children of the root occupy the next three indices.",[range(0,30),trits,[0,1]],(a,b,c)=>a<c?-1:3*(a-c)+(b+1)+1+c,"if(a<c){return 0-1;}return 3*(a-c)+(b+1)+1+c;","if(a<c){return 0-1;}return 2*(a-c)+(b+1)+1+c;");
task("algorithms",4,"Reduce a ternary window","a packs five balanced trits as offset symbols (0,1,2), low-first. Reduce the first c values (c=1..5). b=0 sum, b=1 minimum, b=2 maximum. Return a signed integer.",[range(0,242),symbols,range(1,5)],(a,b,c)=>{const x=digits(a,5).slice(0,c).map(v=>v-1);return b===0?x.reduce((s,v)=>s+v,0):b===1?Math.min(...x):Math.max(...x);},"var r:t40=digit(a,0)-1;var i:t40=1;while(i<c){var x:t40=digit(a,i)-1;if(b==0){r=r+x;}if(b==1){r=lo(r,x);}if(b==2){r=hi(r,x);}i=i+1;}return r;","var r:t40=0;var i:t40=0;while(i<c){var x:t40=digit(a,i)-1;if(b==0){r=r+x;}if(b==1){r=lo(r,x);}if(b==2){r=hi(r,x);}i=i+1;}return r;");
task("algorithms",5,"Representation-aware transition count","a packs six offset-coded balanced trits, low-first. Count adjacent pairs starting at index c (0..4) whose signed difference equals b (-2..2). Pairs are (i,i+1); do not wrap the last to the first.",[range(0,728),range(-2,2),range(0,4)],(a,b,c)=>{const d=digits(a,6);let n=0;for(let i=c;i<5;i++)if(d[i+1]-d[i]===b)n++;return n;},"var n:t40=0;var i:t40=c;while(i<5){if(digit(a,i+1)-digit(a,i)==b){n=n+1;}i=i+1;}return n;","var n:t40=0;var i:t40=c;while(i<6){if(digit(a,mod(i+1,6))-digit(a,i)==b){n=n+1;}i=i+1;}return n;");
task("algorithms",6,"Choose a cost-minimal ternary batch plan","Process at least a items (0..20). A scalar operation processes one item at cost b; a ternary batch processes three at cost c. Both costs are positive. Overprocessing is allowed. Return the minimal total cost.",[range(0,20),range(1,9),range(1,15)],(a,b,c)=>Math.min(...range(0,Math.ceil(a/3)).map(n=>n*c+Math.max(0,a-3*n)*b)),"var best:t40=a*b;var n:t40=0;while(3*n<a+3){var r:t40=hi(0,a-3*n);best=lo(best,n*c+r*b);n=n+1;}return best;","return q(a,3)*c+mod(a,3)*b;");

task("debugging",1,"Repair a negative carry defect","Repair the starter so adding a,b wraps to a signed c-trit word; c=1..4. Negative overflow must wrap as well as positive overflow.",[range(-40,40),[-13,-4,-1,0,1,4,13],range(1,4)],(a,b,c)=>balanced(a+b,c),"return wrap(a+b,c);","var n:t40=a+b;var w:t40=p3(c);var h:t40=q(w-1,2);while(n>h){n=n-w;}return n;");
task("debugging",2,"Repair a lost unknown result","Compare trits a and b for logical equivalence: if either is unknown, return policy c (-1,0,1); otherwise return +1 for equality and -1 for inequality. The starter treats numeric zero as ordinary equality.",small,(a,b,c)=>a===0||b===0?c:a===b?1:-1,"if(a==0){return c;}if(b==0){return c;}if(a==b){return 1;}return 0-1;","if(a==b){return 1;}return 0-1;");
task("debugging",3,"Repair an invalid compiler rewrite","Return truncTowardZero(((a+b)*c)/3). The starter distributes division across a and b, which changes results when either product has a remainder or products have opposite signs.",[range(-7,7),range(-7,7),range(-3,3)],(a,b,c)=>Number((BigInt(a)+BigInt(b))*BigInt(c)/3n),"return q((a+b)*c,3);","return q(a*c,3)+q(b*c,3);");
task("debugging",4,"Repair a ternary wire codec","Wire symbols encode -1 as 2, 0 as 0, +1 as 1 in base-three positions. Serialize signed trits a,b,c in little-endian order. Return the nonnegative packed integer; the wire alphabet is not the offset alphabet.",small,(a,b,c)=>[a,b,c].reduce((n,x,i)=>n+(x<0?2:x)*3**i,0),"var x:t40=a;var y:t40=b;var z:t40=c;if(x<0){x=2;}if(y<0){y=2;}if(z<0){z=2;}return x+3*y+9*z;","return (a+1)+3*(b+1)+9*(c+1);");
task("debugging",5,"Repair overlapping ternary writes","a packs four unsigned base-three cells, low-first. Copy two cells from index b to index c, with b,c in 0..2. Reads must use the original snapshot, like memmove; return the resulting packed value.",[range(0,80),symbols,symbols],(a,b,c)=>{const d=digits(a,4),original=[...d];d[c]=original[b];d[c+1]=original[b+1];return pack(d);},"var x:t40=digit(a,b);var y:t40=digit(a,b+1);return a+(x-digit(a,c))*p3(c)+(y-digit(a,c+1))*p3(c+1);","var r:t40=a+(digit(a,b)-digit(a,c))*p3(c);return r+(digit(r,b+1)-digit(r,c+1))*p3(c+1);");
task("debugging",6,"Repair a cross-layer span calculation","A request starts at trit offset a and spans b trits, in memory words of c trits (3,9,27). Return words touched: 0 if b=0, otherwise ceil(((a mod c)+b)/c). a,b are nonnegative. A span crossing a partial first word must include it.",[range(0,28),range(0,28),[3,9,27]],(a,b,c)=>b===0?0:Math.ceil((a%c+b)/c),"if(b==0){return 0;}return q(mod(a,c)+b+c-1,c);","if(b==0){return 0;}return q(b+c-1,c);");

task("systems",1,"Lay out an ABI record","A record contains a header of a trits, a payload of b trits aligned to 3 trits, then c trailing trits. The whole record is padded to 9-trit alignment. a,b,c are nonnegative. Return total size, including internal and final padding.",[range(0,12),range(0,12),range(0,4)],(a,b,c)=>9*Math.ceil((3*Math.ceil(a/3)+b+c)/9),"var payload:t40=3*q(a+2,3);return 9*q(payload+b+c+8,9);","return 9*q(a+b+c+8,9);");
task("systems",2,"Place an aligned bounded buffer","Align address a upward to 3^c, then allocate b trits. The arena is [0,729); an empty span may end at 729. Return aligned start if the entire span fits; otherwise return -1. a=0..729,b=0..81,c=0..4.",[[0,1,2,8,9,26,27,80,81,242,243,700,728,729],[0,1,2,8,27,80,81],range(0,4)],(a,b,c)=>{const p=3**c,n=Math.ceil(a/p)*p;return n+b<=729?n:-1;},"var p:t40=p3(c);var s:t40=q(a+p-1,p)*p;if(s+b>729){return 0-1;}return s;","var p:t40=p3(c);var s:t40=q(a,p)*p;if(s+b>729){return 0-1;}return s;");
task("systems",3,"Check a guest memory contract","a is span start, b length, c exclusive memory limit. Return +1 iff all are nonnegative and [a,a+b) lies within [0,c), allowing empty spans at c; otherwise -1. Do not use overflow-prone addition for the bounds comparison.",[[-1,0,1,2,26,27,80,81,728,729],[-1,0,1,2,27,81,729],[0,1,27,81,729]],(a,b,c)=>a>=0&&b>=0&&c>=0&&BigInt(a)<=BigInt(c)&&BigInt(b)<=BigInt(c)-BigInt(a)?1:-1,"if(a<0){return 0-1;}if(b<0){return 0-1;}if(c<0){return 0-1;}if(a>c){return 0-1;}if(b>c-a){return 0-1;}return 1;","if(a<0){return 0-1;}if(b<0){return 0-1;}if(a+b>=c){return 0-1;}return 1;");
task("systems",4,"Translate a syscall boundary result","a is native return code, b is pointer-valid flag (0/1), c is retry-enabled flag (0/1). Invalid pointer always yields -1. Otherwise nonnegative a yields +1, a=-2 yields 0 only when retry is enabled, and all other negatives yield -1.",[[-9,-3,-2,-1,0,1,3,9],[0,1],[0,1]],(a,b,c)=>!b?-1:a>=0?1:a===-2&&c?0:-1,"if(b==0){return 0-1;}if(a>=0){return 1;}if(a==0-2){if(c==1){return 0;}}return 0-1;","if(b==0){return 0-1;}if(a>0){return 1;}if(a==0-2){if(c==1){return 0;}}return 0-1;");
task("systems",5,"Recover a ternary journal","a packs five journal events low-first: 0=no-op, 1=stage value c+eventIndex, 2=commit latest staged value if one exists. Initial durable value is b. A crash follows the fifth event. Return the durable value; uncommitted writes disappear.",[range(0,242),range(-2,2),range(-2,2)],(a,b,c)=>{let durable=b,pending:number|null=null;digits(a,5).forEach((e,i)=>{if(e===1)pending=c+i;if(e===2&&pending!==null){durable=pending;pending=null;}});return durable;},"var durable:t40=b;var pending:t40=0;var valid:t40=0;var i:t40=0;while(i<5){var e:t40=digit(a,i);if(e==1){pending=c+i;valid=1;}if(e==2){if(valid==1){durable=pending;valid=0;}}i=i+1;}return durable;","var durable:t40=b;var i:t40=0;while(i<5){if(digit(a,i)==1){durable=c+i;}i=i+1;}return durable;");
task("systems",6,"Schedule three priority queues","a,b,c are job counts for queues 0,1,2. Run 13 ticks, targeting repeating queues [2,1,2,0]. If target is empty, choose highest numbered nonempty queue. Stop if all empty. Return completed0 + 27*completed1 + 729*completed2.",[range(0,10),range(0,10),range(0,10)],(a,b,c)=>{const left=[a,b,c],done=[0,0,0];for(let i=0;i<13;i++){let k=[2,1,2,0][i%4];if(!left[k])k=left[2]?2:left[1]?1:left[0]?0:-1;if(k<0)break;left[k]--;done[k]++;}return done[0]+27*done[1]+729*done[2];},"var x:t40=a;var y:t40=b;var z:t40=c;var r:t40=0;var i:t40=0;while(i<13){var k:t40=2;if(mod(i,4)==1){k=1;}if(mod(i,4)==3){k=0;}var empty:t40=0;if(k==0){if(x==0){empty=1;}}if(k==1){if(y==0){empty=1;}}if(k==2){if(z==0){empty=1;}}if(empty==1){if(z>0){k=2;}else{if(y>0){k=1;}else{if(x>0){k=0;}else{return r;}}}}if(k==0){x=x-1;r=r+1;}if(k==1){y=y-1;r=r+27;}if(k==2){z=z-1;r=r+729;}i=i+1;}return r;","var z:t40=lo(c,13);var y:t40=lo(b,13-z);var x:t40=lo(a,13-z-y);return x+27*y+729*z;");

function rng(seed: number) { let state=seed>>>0; return () => { state=(Math.imul(state,1664525)+1013904223)>>>0; return state/4294967296; }; }
function inputs(d: Definition): Array<[number,number,number]> {
  const [a,b,c]=d.domain, result:Array<[number,number,number]>=[], seen=new Set<string>();
  const add=(v:[number,number,number])=>{const key=v.join(",");if(!seen.has(key)){seen.add(key);result.push(v);}};
  if(a.length*b.length*c.length<=125) for(const x of a) for(const y of b) for(const z of c) add([x,y,z]);
  else {
    // Include boundary corners and a fixed sample from each declared input domain.
    for(const x of [a[0],a.at(-1)!]) for(const y of [b[0],b.at(-1)!]) for(const z of [c[0],c.at(-1)!]) add([x,y,z]);
    const random=rng(parseInt(hash(d.id).slice(0,8),16));
    while(result.length<96) add([a[Math.floor(random()*a.length)],b[Math.floor(random()*b.length)],c[Math.floor(random()*c.length)]]);
  }
  const random=rng(parseInt(hash(d.id+REVISION).slice(0,8),16));
  for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}
  return result;
}
const CHECKER_HASH = hash(fs.readFileSync(path.join(import.meta.dir,"corpus.ts")));
export function corpus(): TaskPackage[] {
  return defs.map(d=>{
    const all=inputs(d).map((args,i)=>({id:`${d.id}:case:${i}`,args,expected:d.oracle(...args)}));
    invariant(all.every(x=>Number.isSafeInteger(x.expected)),"Oracle must produce exact integer results.");
    const size=Math.floor((all.length-9)/3);
    const targets=all.map(x=>x.id);
    const p={id:d.id,capability:d.capability,difficulty:d.difficulty,title:d.title,requirements:d.requirements,
      specification:LANGUAGE_REFERENCE,starter:{"solution.trit":d.capability==="debugging"?d.wrong:source("return 0;")},
      reference:d.reference,mutants:[{name:"semantic-defect",source:d.wrong,targetCaseIds:targets},
        {name:"constant-shortcut",source:source("return 0;"),targetCaseIds:targets},
        {name:"off-by-one-output",source:d.reference.replace("fn solve(","fn candidate(")+"\nfn solve(a:t40,b:t40,c:t40)->t40{return candidate(a,b,c)+1;}",targetCaseIds:targets}],
      publicCases:all.slice(0,3),privateCases:all.slice(3),feedback:[all.slice(3,5),all.slice(5,7),all.slice(7,9)],
      probes:[all.slice(9,9+size),all.slice(9+size,9+2*size),all.slice(9+2*size)],qualificationCases:all,exhaustive:d.domain.reduce((size,axis)=>size*axis.length,1)<=125,
      invariants:["Deterministic pure function of three exact integer inputs.","All declared cases use exact integer or rational oracles.","Probe input triples are disjoint from demonstrations and feedback."],checkerHash:CHECKER_HASH};
    return {...p,packageHash:hash(p)};
  });
}
export function family(id:string):TaskPackage { const p=corpus().find(t=>t.id===id);invariant(p,"Unknown task family.");return p; }
