#!/usr/bin/env python3
"""Generate the architecture v2 contracts from ARCHITECTURE_MANIFEST.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "ARCHITECTURE_MANIFEST.json"
HEADER = REPO / "generated" / "architecture_contract.h"
TCL = REPO / "generated" / "architecture_contract.trit"
DOC = REPO / "docs" / "04_Binary_Contract" / "architecture_v2.md"


def load_manifest() -> dict:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if data.get("schema") != "trit.architecture_manifest.v1":
        raise ValueError("unsupported architecture manifest schema")
    return data


def upper_name(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name.upper())


def render_header(data: dict) -> str:
    arch = data["architecture"]
    abi = data["abi"]
    isa = data["isa"]
    pte = data["pte_v2"]
    tlb = data["tlb"]
    formats = data["formats"]
    header_fields = data["executable_header_v2"]["fields"]
    vctx = isa["v3_private_extensions"]["vector_context"]

    lines = [
        "// Generated by tools/generate_architecture_contract.py. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace sandbox::architecture::v2 {",
        f"inline constexpr int ISA_VERSION = {arch['isa_version']};",
        f"inline constexpr int INSTRUCTION_TRITS = {arch['instruction_trits']};",
        f"inline constexpr int SCALAR_WORD_TRITS = {arch['scalar_word_trits']};",
        f"inline constexpr int WIDE_SCALAR_TRITS = {arch['wide_scalar_trits']};",
        f"inline constexpr int STORAGE_BLOCK_WORDS = {arch['storage_block_words']};",
        f"inline constexpr int BASE_PAGE_WORDS = {arch['base_page_words']};",
        f"inline constexpr int SUPERPAGE_WORDS = {arch['superpage_words']};",
        f"inline constexpr int ASID_TRITS = {arch['asid_trits']};",
        f"inline constexpr int STACK_ALIGNMENT_WORDS = {arch['stack_alignment_words']};",
        f"inline constexpr int EXECUTABLE_VERSION = {abi['executable_version']};",
        f"inline constexpr int FUNCTION_ABI_VERSION = {abi['function_abi_version']};",
        f"inline constexpr int SYSCALL_ABI_VERSION = {abi['syscall_abi_version']};",
        f"inline constexpr int CALLEE_SAVED_FIRST = {abi['callee_saved']['first']};",
        f"inline constexpr int CALLEE_SAVED_LAST = {abi['callee_saved']['last']};",
        f"inline constexpr int FUNCTION_ARG_FIRST = {abi['function_arguments']['first']};",
        f"inline constexpr int FUNCTION_ARG_LAST = {abi['function_arguments']['last']};",
        f"inline constexpr int SYSCALL_ARG_FIRST = {abi['syscall_arguments']['first']};",
        f"inline constexpr int SYSCALL_ARG_LAST = {abi['syscall_arguments']['last']};",
        f"inline constexpr int CALLER_SAVED_FIRST = {abi['caller_saved']['first']};",
        f"inline constexpr int CALLER_SAVED_LAST = {abi['caller_saved']['last']};",
        f"inline constexpr int RETURN_LOW = {abi['return_low']};",
        f"inline constexpr int RETURN_HIGH = {abi['return_high']};",
        f"inline constexpr int LINK_REGISTER = {abi['link_register']};",
        f"inline constexpr int STACK_POINTER = {abi['stack_pointer']};",
        f"inline constexpr int EXECUTABLE_HEADER_WORDS = {data['executable_header_v2']['words']};",
        f"inline constexpr int ESCAPE_OPCODE = {isa['escape_opcode']};",
        "inline constexpr std::array<int, "
        f"{len(isa['reserved_direct_values'])}> DIRECT_RESERVED_VALUES = {{",
        "    " + ", ".join(str(value) for value in isa["reserved_direct_values"]),
        "};",
        f"inline constexpr int DIRECT_RESERVED_FIRST = {isa['reserved_direct_first']};",
        f"inline constexpr int DIRECT_RESERVED_LAST = {isa['reserved_direct_last']};",
        f"inline constexpr int PTE_PPN_LSB = {pte['ppn_lsb']};",
        f"inline constexpr int PTE_PPN_WIDTH = {pte['ppn_width']};",
        f"inline constexpr int ITLB_ENTRIES = {tlb['l1_instruction_entries']};",
        f"inline constexpr int DTLB_ENTRIES = {tlb['l1_data_entries']};",
        f"inline constexpr int L1_TLB_WAYS = {tlb['l1_ways']};",
        f"inline constexpr int L2_TLB_ENTRIES = {tlb['l2_entries']};",
        f"inline constexpr int L2_TLB_WAYS = {tlb['l2_ways']};",
        f"inline constexpr int TBOOT_WRITE_VERSION = {formats['tboot_write_version']};",
        f"inline constexpr int TDISK_WRITE_VERSION = {formats['tdisk_write_version']};",
        "",
    ]
    for name, value in isa["direct_opcodes"].items():
        lines.append(f"inline constexpr int OPCODE_{upper_name(name)} = {value};")
    lines.append("")
    for name, value in isa["extension_selectors"].items():
        lines.append(f"inline constexpr int EXT_{upper_name(name)} = {value};")
    lines.append("")
    for name, value in isa["features"].items():
        lines.append(f"inline constexpr int FEATURE_{upper_name(name)} = {value};")
    lines.append("")
    for name, value in isa["csrs"].items():
        lines.append(f"inline constexpr int CSR_{upper_name(name)} = {value};")
    lines.append("")
    for name, value in pte["fields"].items():
        lines.append(f"inline constexpr int PTE_{upper_name(name)} = {value};")
    lines.extend(
        [
            "",
            f"inline constexpr std::array<int, {len(abi['reserved_syscalls'])}> RESERVED_SYSCALLS = {{",
            "    " + ", ".join(str(item) for item in abi["reserved_syscalls"]),
            "};",
            f"inline constexpr std::array<std::string_view, {len(header_fields)}> EXECUTABLE_HEADER_FIELDS = {{",
        ]
    )
    lines.extend(f'    "{field}",' for field in header_fields)
    lines.extend(
        [
            "};",
            "",
            "}  // namespace sandbox::architecture::v2",
            "",
            "namespace sandbox::architecture::v3 {",
            f"inline constexpr int VCTX_WIRE_OPCODE = {vctx['wire_opcode']};",
            f"inline constexpr int VCTX_REGISTER_LSB = {vctx['register_lsb']};",
            f"inline constexpr int VCTX_REGISTER_WIDTH = {vctx['register_width']};",
            f"inline constexpr int VCTX_SELECTOR_LSB = {vctx['selector_lsb']};",
            f"inline constexpr int VCTX_SELECTOR_WIDTH = {vctx['selector_width']};",
            f"inline constexpr int VCTX_RESERVED_LSB = {vctx['reserved_lsb']};",
            f"inline constexpr int VCTX_RESERVED_WIDTH = {vctx['reserved_width']};",
            f"inline constexpr int VCTX_OFFSET_LSB = {vctx['offset_lsb']};",
            f"inline constexpr int VCTX_OFFSET_WIDTH = {vctx['offset_width']};",
        ]
    )
    for name, value in vctx["selectors"].items():
        lines.append(f"inline constexpr int {upper_name(name)}_SELECTOR = {value};")
    lines.extend(["}  // namespace sandbox::architecture::v3", ""])
    return "\n".join(lines)


def render_tcl(data: dict) -> str:
    arch = data["architecture"]
    abi = data["abi"]
    isa = data["isa"]
    pte = data["pte_v2"]
    tlb = data["tlb"]
    constants = {
        "ARCH_ISA_VERSION": arch["isa_version"],
        "ARCH_INSTRUCTION_TRITS": arch["instruction_trits"],
        "ARCH_SCALAR_WORD_TRITS": arch["scalar_word_trits"],
        "ARCH_WIDE_SCALAR_TRITS": arch["wide_scalar_trits"],
        "ARCH_STORAGE_BLOCK_WORDS": arch["storage_block_words"],
        "ARCH_BASE_PAGE_WORDS": arch["base_page_words"],
        "ARCH_SUPERPAGE_WORDS": arch["superpage_words"],
        "ARCH_ASID_TRITS": arch["asid_trits"],
        "ARCH_STACK_ALIGNMENT_WORDS": arch["stack_alignment_words"],
        "ARCH_EXECUTABLE_VERSION": abi["executable_version"],
        "ARCH_FUNCTION_ABI_VERSION": abi["function_abi_version"],
        "ARCH_SYSCALL_ABI_VERSION": abi["syscall_abi_version"],
        "ARCH_FUNCTION_ARG_FIRST": abi["function_arguments"]["first"],
        "ARCH_FUNCTION_ARG_LAST": abi["function_arguments"]["last"],
        "ARCH_SYSCALL_ARG_FIRST": abi["syscall_arguments"]["first"],
        "ARCH_SYSCALL_ARG_LAST": abi["syscall_arguments"]["last"],
        "ARCH_RETURN_LOW": abi["return_low"],
        "ARCH_RETURN_HIGH": abi["return_high"],
        "ARCH_LINK_REGISTER": abi["link_register"],
        "ARCH_STACK_POINTER": abi["stack_pointer"],
        "ARCH_OPCODE_EXT": isa["escape_opcode"],
        "ARCH_PTE_PPN_LSB": pte["ppn_lsb"],
        "ARCH_PTE_PPN_WIDTH": pte["ppn_width"],
        "ARCH_ITLB_ENTRIES": tlb["l1_instruction_entries"],
        "ARCH_DTLB_ENTRIES": tlb["l1_data_entries"],
        "ARCH_L2_TLB_ENTRIES": tlb["l2_entries"],
    }
    for name, value in isa["features"].items():
        constants[f"ARCH_FEATURE_{upper_name(name)}"] = value
    for name, value in isa["csrs"].items():
        constants[f"ARCH_CSR_{upper_name(name)}"] = value
    for name, value in pte["fields"].items():
        constants[f"ARCH_PTE_{upper_name(name)}"] = value

    lines = [
        "// Generated by tools/generate_architecture_contract.py. Do not edit.",
        "// Import this module from v2 kernel/runtime sources.",
        "",
    ]
    lines.extend(f"const {name}: t40 = {value};" for name, value in constants.items())
    lines.append("")
    return "\n".join(lines)


def render_doc(data: dict) -> str:
    arch = data["architecture"]
    abi = data["abi"]
    isa = data["isa"]
    pte = data["pte_v2"]
    lines = [
        "<!-- Generated by tools/generate_architecture_contract.py. Do not edit. -->",
        "# Architecture v2 Contract",
        "",
        "`ARCHITECTURE_MANIFEST.json` is authoritative. Regenerate with",
        "`python tools/generate_architecture_contract.py`.",
        "",
        f"**Design goal:** {arch['design_goal']}. This goal applies to {arch['design_goal_scope']}:",
        f"T{arch['scalar_word_trits']} is the largest whole-trit word whose valid ternary state space fits in 64 bits",
        f"(`3^{arch['scalar_word_trits']} < 2^64 < 3^{arch['scalar_word_trits'] + 1}`). It describes scalar capacity and software role,",
        "not binary compatibility or the physical size of every host/wire encoding. Instruction width, vector lane count, and explicit wide values are independent contracts.",
        "",
        "## Native geometry",
        "",
        "| Contract | Value |",
        "|---|---:|",
        f"| ISA version | {arch['isa_version']} |",
        f"| Instruction word | {arch['instruction_trits']} trits |",
        f"| Scalar register/memory word | T{arch['scalar_word_trits']} |",
        f"| Wide scalar | T{arch['wide_scalar_trits']} in a pair/extension state |",
        f"| Storage block | {arch['storage_block_words']} words |",
        f"| Base page | {arch['base_page_words']} words |",
        f"| Superpage | {arch['superpage_words']} words |",
        f"| ASID | {arch['asid_trits']} trits |",
        "",
        "## ABI",
        "",
        f"- Function ABI v{abi['function_abi_version']}: arguments r{abi['function_arguments']['first']}–r{abi['function_arguments']['last']}.",
        f"- Syscall ABI v{abi['syscall_abi_version']}: arguments r{abi['syscall_arguments']['first']}–r{abi['syscall_arguments']['last']}.",
        f"- T40 return in r{abi['return_low']}; T50 return in r{abi['return_low']}:r{abi['return_high']}.",
        f"- Stack alignment is {arch['stack_alignment_words']} T40 words.",
        f"- Syscalls {', '.join(str(item) for item in abi['reserved_syscalls'])} are permanently reserved in v2.",
        "",
        "## Direct ISA v2 opcodes",
        "",
        "| Mnemonic | Opcode |",
        "|---|---:|",
    ]
    lines.extend(f"| `{name}` | {value} |" for name, value in isa["direct_opcodes"].items())
    lines.extend(
        [
            "",
            "Unassigned direct opcode "
            + ", ".join(str(value) for value in isa["reserved_direct_values"])
            + " and direct opcodes "
            + f"{isa['reserved_direct_first']}–{isa['reserved_direct_last']} are reserved.",
            "Opcode 80 is the v2 extension escape; no v1 operation encoding is accepted by production assemblers or VMs.",
            "",
            "## PTE v2",
            "",
            "Zero is non-present. Flag trits must be zero or positive; negative flags are invalid.",
            "",
            "| Trit | Field |",
            "|---:|---|",
        ]
    )
    lines.extend(f"| {value} | `{name.lower()}` |" for name, value in pte["fields"].items())
    lines.extend(
        [
            "",
            f"Physical base-page number occupies trits {pte['ppn_lsb']}–39.",
            "Superpage PPNs are aligned to 27 base pages.",
            "",
        ]
    )
    return "\n".join(lines)


def expected_outputs(data: dict) -> dict[Path, str]:
    return {
        HEADER: render_header(data),
        TCL: render_tcl(data),
        DOC: render_doc(data),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated outputs drift")
    args = parser.parse_args()
    data = load_manifest()
    outputs = expected_outputs(data)
    if args.check:
        drift = []
        for path, content in outputs.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(REPO)))
        if drift:
            print("architecture contract drift: " + ", ".join(drift), file=sys.stderr)
            return 1
        print("architecture contract generated outputs are current")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
